-- =============================================================================
-- 08_view.sql
-- Vistas del schema public.
--
-- Aplicar después de 02_tables.sql.
-- =============================================================================

-- Sin vistas en el schema public.
--
-- public.audit_log_view fue eliminada en prod en Fase 5.D (normalización de
-- nombres): vista huérfana sin consumidores que leía la columna legacy
-- profiles.nombre. Versionado del DROP en
-- 20260624_nombres_02_drop_audit_log_view.sql.
