export const ESPECIALIDADES = [
  'Medicina Interna',
  'Cardiología',
  'Neumología',
  'Gastroenterología',
  'Endocrinología',
  'Nefrología',
  'Neurología',
  'Hematología',
  'Reumatología',
  'Infectología',
  'Oncología Médica',
  'Geriatría',
  'Dermatología',
  'Cirugía General',
  'Ortopedia y Traumatología',
  'Cirugía de Columna',
  'Neurocirugía',
  'Cirugía Cardiovascular',
  'Otorrinolaringología',
  'Oftalmología',
  'Urología',
  'Cirugía Plástica, Estética y Reconstructiva',
  'Cirugía Pediátrica',
  'Pediatría',
  'Ginecología y Obstetricia',
  'Neonatología',
  'Radiología e Imagenología',
  'Patología Clínica',
  'Anestesiología',
  'Medicina de Rehabilitación',
  'Medicina de Urgencias',
  'Psiquiatría',
  'Medicina Familiar y Comunitaria',
  'Medicina del Deporte',
  'Genética Médica',
  'Medicina Legal y Forense',
] as const
