export const ESTUDIOS_LAB: string[] = [
  // ── Perfiles / Paneles ──────────────────────────────────────────────────────
  'Biometría Hemática Completa (BHC)',
  'Química Sanguínea 6 elementos',
  'Química Sanguínea 27 elementos',
  'Panel Metabólico Básico',
  'Panel Metabólico Completo',
  'Perfil Hepático',
  'Perfil Renal',
  'Perfil Lipídico Completo',
  'Perfil Tiroideo Completo',
  'Perfil de Anemia',
  'Perfil Reumatológico',
  'Perfil Hormonal Femenino',
  'Perfil Hormonal Masculino',
  'Perfil Prenatal Básico',
  'Panel de Coagulación',
  'Perfil TORCH',
  'Perfil de Diabetes',
  'Perfil Nutricional',

  // ── Hematología ─────────────────────────────────────────────────────────────
  'Hemoglobina',
  'Hematocrito',
  'Leucocitos (conteo total)',
  'Fórmula diferencial de leucocitos',
  'Plaquetas',
  'Volumen Plaquetario Medio (VPM)',
  'Reticulocitos',
  'Frotis de Sangre Periférica',
  'Velocidad de Sedimentación Globular (VSG)',
  'Grupo Sanguíneo y Factor Rh',
  'Prueba de Coombs Directa',
  'Prueba de Coombs Indirecta',

  // ── Coagulación ─────────────────────────────────────────────────────────────
  'Tiempo de Protrombina (TP / INR)',
  'Tiempo de Tromboplastina Parcial Activada (TTPa)',
  'Fibrinógeno',
  'Dímero D',
  'Tiempo de Trombina',
  'Antitrombina III',
  'Proteína C',
  'Proteína S',
  'Factor V de Leiden',
  'Anticoagulante lúpico',

  // ── Química sanguínea básica ────────────────────────────────────────────────
  'Glucosa en ayuno',
  'Glucosa postprandial (2 h)',
  'Urea',
  'Nitrógeno Ureico (BUN)',
  'Creatinina',
  'Ácido Úrico',
  'Bilirrubina Total',
  'Bilirrubina Directa',
  'Bilirrubina Indirecta',
  'Proteínas Totales',
  'Albúmina',
  'Globulinas',

  // ── Enzimas / Función hepática ──────────────────────────────────────────────
  'TGO (AST)',
  'TGP (ALT)',
  'Fosfatasa Alcalina',
  'GGT (Gamma-Glutamil Transferasa)',
  'LDH (Deshidrogenasa Láctica)',
  'CPK (Creatinina Fosfocinasa)',
  'CPK-MB',
  'Amilasa',
  'Lipasa',
  'Troponina I',
  'Troponina T ultrasensible',

  // ── Lípidos ─────────────────────────────────────────────────────────────────
  'Colesterol Total',
  'HDL Colesterol',
  'LDL Colesterol',
  'VLDL Colesterol',
  'Triglicéridos',
  'Índice Aterogénico',
  'Apolipoproteína A1',
  'Apolipoproteína B',
  'Lipoproteína (a)',

  // ── Función renal ───────────────────────────────────────────────────────────
  'Cistatina C',
  'Tasa de Filtración Glomerular Estimada (TFGe)',
  'Microalbuminuria',
  'Proteínas en Orina 24 h',
  'Creatinina en Orina 24 h',
  'Depuración de Creatinina',
  'Relación Albúmina/Creatinina en orina',

  // ── Electrolitos ─────────────────────────────────────────────────────────────
  'Sodio',
  'Potasio',
  'Cloro',
  'Calcio Total',
  'Calcio Iónico',
  'Magnesio',
  'Fósforo',
  'Bicarbonato',
  'Osmolalidad sérica',

  // ── Tiroides ────────────────────────────────────────────────────────────────
  'TSH',
  'T3 Libre',
  'T4 Libre',
  'T3 Total',
  'T4 Total',
  'Anti-TPO (anticuerpos antiperoxidasa)',
  'Anti-Tiroglobulina',
  'Tiroglobulina',
  'Captación de T3',

  // ── Vitaminas y minerales ───────────────────────────────────────────────────
  'Vitamina D 25-OH',
  'Vitamina B12 (Cobalamina)',
  'Ácido Fólico (Vitamina B9)',
  'Vitamina A (Retinol)',
  'Vitamina E (Tocoferol)',
  'Vitamina C',
  'Vitamina K',
  'Hierro Sérico',
  'Ferritina',
  'Transferrina',
  'Saturación de Transferrina',
  'TIBC (Capacidad Total de Unión al Hierro)',
  'Zinc Sérico',
  'Cobre Sérico',
  'Selenio',
  'Yodo en Orina',
  'Manganeso',

  // ── Glucometabolismo ─────────────────────────────────────────────────────────
  'Hemoglobina Glucosilada (HbA1c)',
  'Insulina Basal',
  'Péptido C',
  'HOMA-IR',
  'Curva de Tolerancia a la Glucosa 75 g (2 h)',
  'Curva de Tolerancia a la Glucosa 75 g (3 h)',
  'Curva de Insulina',
  'Fructosamina',

  // ── Hormonas ─────────────────────────────────────────────────────────────────
  'Cortisol Basal (8 am)',
  'Cortisol Post-estimulación (ACTH)',
  'DHEA-S (Dehidroepiandrosterona-S)',
  'Testosterona Total',
  'Testosterona Libre',
  'Testosterona Biodisponible',
  'Estradiol (E2)',
  'Estrona',
  'Progesterona',
  'FSH (Hormona Folículo Estimulante)',
  'LH (Hormona Luteinizante)',
  'Prolactina',
  'Hormona del Crecimiento (GH)',
  'IGF-1 (Somatomedina C)',
  'ACTH',
  'Aldosterona',
  'Renina',
  'PTH (Parathormona)',
  'Calcitonina',
  'Beta-HCG cuantitativa',
  'AMH (Hormona Antimülleriana)',
  'Inhibina B',
  'Androstenediona',
  '17-Hidroxiprogesterona',

  // ── Marcadores inflamatorios ─────────────────────────────────────────────────
  'PCR (Proteína C Reactiva)',
  'PCR Ultrasensible (hs-CRP)',
  'Procalcitonina',
  'Interleucina-6 (IL-6)',
  'Factor de Necrosis Tumoral Alfa (TNF-α)',

  // ── Marcadores tumorales ─────────────────────────────────────────────────────
  'PSA Total (Antígeno Prostático Específico)',
  'PSA Libre',
  'Relación PSA Libre/Total',
  'CEA (Antígeno Carcinoembrionario)',
  'AFP (Alfafetoproteína)',
  'CA 125',
  'CA 15-3',
  'CA 19-9',
  'CA 72-4',
  'Beta-HCG (marcador tumoral)',
  'NSE (Enolasa Neuroespecífica)',
  'Cromogranina A',
  'Antígeno de Células Escamosas (SCC)',
  'HE4',
  'Proteína ROMA',

  // ── Reumatología / Autoinmunidad ─────────────────────────────────────────────
  'Factor Reumatoide',
  'Anti-CCP (Anti-Péptido Cíclico Citrulinado)',
  'ANA (Anticuerpos Antinucleares)',
  'Anti-DNA de Doble Cadena',
  'ANCA (Anti-citoplasma de Neutrófilos)',
  'Complemento C3',
  'Complemento C4',
  'Complemento CH50',
  'Anti-Sm',
  'Anti-SSA (Ro)',
  'Anti-SSB (La)',
  'Anti-Jo-1',
  'Anti-Scl-70',
  'Anti-centrómero',
  'Anti-histona',
  'Crioglobulinas',
  'HLA-B27',
  'Beta-2 Microglobulina',
  'Anticuerpos antifosfolípidos',
  'Anticuerpos anti-β2 glicoproteína I',

  // ── Inmunología ──────────────────────────────────────────────────────────────
  'IgA Total',
  'IgG Total',
  'IgM Total',
  'IgE Total',
  'IgE Específica (panel de alergias)',
  'Subpoblaciones de Linfocitos (CD4/CD8)',
  'CD4 absoluto',
  'CD8 absoluto',

  // ── Urianálisis ──────────────────────────────────────────────────────────────
  'Examen General de Orina (EGO)',
  'Sedimento Urinario',
  'Urocultivo y Antibiograma',
  'Orina 24 h — Proteínas',
  'Orina 24 h — Creatinina',
  'Orina 24 h — Cortisol',
  'Orina 24 h — Calcio',
  'Orina 24 h — Ácido Úrico',
  'Orina 24 h — Catecolaminas',
  'Orina 24 h — Metanefrinas',
  'Orina 24 h — Ácido Vanililmandélico (AVM)',

  // ── Microbiología / Cultivos ─────────────────────────────────────────────────
  'Hemocultivo (x2)',
  'Coprocultivo',
  'Cultivo de Esputo',
  'Cultivo de Herida',
  'Cultivo de Secreción',
  'Cultivo de LCR',
  'Cultivo para Hongos (Micológico)',
  'Cultivo para Micobacterias (BAAR)',
  'Baciloscopia (BAAR)',
  'Antibiograma',
  'KOH (Búsqueda de Hongos)',
  'Examen Coproparasitoscópico (CPS)',
  'Examen Coproparasitoscópico en serie (3)',
  'Sangre Oculta en Heces',

  // ── Serología / Infecciosas ──────────────────────────────────────────────────
  'VIH 1 y 2 (ELISA)',
  'Carga Viral VIH',
  'VDRL (Sífilis)',
  'FTA-ABS',
  'RPR',
  'Hepatitis B — HBsAg (antígeno de superficie)',
  'Hepatitis B — Anti-HBs',
  'Hepatitis B — Anti-HBc Total',
  'Hepatitis B — Anti-HBc IgM',
  'Hepatitis B — HBeAg',
  'Hepatitis B — Carga Viral (DNA)',
  'Hepatitis C — Anticuerpos',
  'Hepatitis C — Carga Viral (RNA)',
  'Hepatitis A — IgM',
  'Hepatitis A — IgG',
  'Hepatitis E — IgM',
  'Toxoplasma IgG',
  'Toxoplasma IgM',
  'CMV (Citomegalovirus) IgG/IgM',
  'EBV (Epstein-Barr) — anticuerpos',
  'Herpes Simple IgG/IgM',
  'Rubéola IgG',
  'Rubéola IgM',
  'TORCH Completo',
  'Dengue — NS1 antígeno',
  'Dengue — IgM/IgG',
  'Influenza A/B antígeno',
  'COVID-19 Antígeno',
  'COVID-19 PCR',
  'COVID-19 IgG/IgM',
  'H. pylori Anticuerpos IgG',
  'H. pylori Antígeno en Heces',
  'H. pylori Prueba de Aliento (Urea-13C)',
  'Chagas (Trypanosoma cruzi)',
  'Brucella aglutinaciones',
  'Reacción de Widal (Salmonella)',
  'Leptospira anticuerpos',
  'Paludismo (Plasmodium) gota gruesa',
  'Rickettsia anticuerpos',
  'Parvovirus B19 IgM/IgG',
  'Varicela Zoster IgG/IgM',

  // ── Gasometría ───────────────────────────────────────────────────────────────
  'Gasometría Arterial',
  'Gasometría Venosa',
  'Lactato',
  'Oximetría de pulso',

  // ── Líquidos corporales ──────────────────────────────────────────────────────
  'Análisis de Líquido Sinovial',
  'Análisis de Líquido Cefalorraquídeo (LCR)',
  'Análisis de Líquido Pleural',
  'Análisis de Líquido Ascítico',
  'Análisis de Líquido Pericárdico',
  'Cristales en Líquido Sinovial',

  // ── Endocrinología especial ──────────────────────────────────────────────────
  'Test de Supresión con Dexametasona (1 mg)',
  'Test de Supresión con Dexametasona (2 mg × 2 días)',
  'Test de Estimulación con ACTH (Synacthen)',
  'Metanefrinas Plasmáticas',
  'Catecolaminas en Plasma',

  // ── Biología molecular / Genética ───────────────────────────────────────────
  'PCR para Influenza A/B',
  'PCR para VRS (Virus Sincitial Respiratorio)',
  'Cariotipo',
  'FISH',
  'Array-CGH',
  'Estudio de mutación BRCA1/BRCA2',
  'Farmacogenómica básica',

  // ── Otros estudios frecuentes ────────────────────────────────────────────────
  'Prueba de Embarazo (Beta-HCG orina)',
  'Examen de Semen (Espermatobioscopía)',
  'Prueba de Función Suprarrenal',
  'Punción Lumbar — Citoquímico de LCR',
  'Nitrógeno Ureico en Orina',
  'Sodio en Orina',
  'Potasio en Orina',
  'Cloro en Orina',
  'Osmolalidad en Orina',
]
