-- ============================================================
-- MIGRACIÓN: Tabla de medicamentos
-- ============================================================

CREATE TABLE IF NOT EXISTS medicamentos (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre_comercial text NOT NULL,
  principio_activo text NOT NULL,
  presentacion     text NOT NULL,
  dosis_sugerida   text NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);

-- ── Índices para búsqueda rápida por ilike ──────────────────
CREATE INDEX IF NOT EXISTS idx_medicamentos_nombre_comercial
  ON medicamentos (nombre_comercial);

CREATE INDEX IF NOT EXISTS idx_medicamentos_principio_activo
  ON medicamentos (principio_activo);

-- ── Row-Level Security ──────────────────────────────────────
ALTER TABLE medicamentos ENABLE ROW LEVEL SECURITY;

-- Solo lectura para usuarios autenticados
CREATE POLICY "Lectura para usuarios autenticados"
  ON medicamentos
  FOR SELECT
  TO authenticated
  USING (true);

-- ============================================================
-- DATOS
-- ============================================================

INSERT INTO medicamentos (nombre_comercial, principio_activo, presentacion, dosis_sugerida) VALUES
-- ── AINEs / ANALGÉSICOS NO OPIOIDES ────────────────────────
-- Diclofenaco
('Voltaren', 'Diclofenaco sódico', 'Tabletas 50 mg', '1 tableta cada 8 hrs con alimentos por 5-7 días'),
('Voltaren Retard', 'Diclofenaco sódico', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 24 hrs con alimentos'),
('Cataflam', 'Diclofenaco potásico', 'Tabletas 50 mg', '1 tableta cada 8 hrs con alimentos por 5-7 días'),
('Diclofenaco', 'Diclofenaco sódico', 'Solución inyectable 75 mg/3 ml', '75 mg IM cada 12-24 hrs, máximo 2 días'),
('Diclofenaco', 'Diclofenaco sódico', 'Tabletas 25 mg', '1-2 tabletas cada 8 hrs con alimentos'),
-- Dexketoprofeno
('Keral', 'Dexketoprofeno trometamol', 'Tabletas 25 mg', '1 tableta cada 8 hrs con alimentos por 5-7 días'),
('Keral', 'Dexketoprofeno trometamol', 'Solución inyectable 50 mg/2 ml', '50 mg IM/IV cada 8-12 hrs, máximo 2 días'),
('Dexketoprofeno', 'Dexketoprofeno trometamol', 'Tabletas 25 mg', '1 tableta cada 8 hrs con alimentos'),
('Enantyum', 'Dexketoprofeno trometamol', 'Tabletas 25 mg', '1 tableta cada 8 hrs con alimentos por 5-7 días'),
('Enantyum', 'Dexketoprofeno trometamol', 'Sobres granulado 25 mg', '1 sobre disuelto en agua cada 8 hrs'),
-- Ketoprofeno
('Profenid', 'Ketoprofeno', 'Cápsulas 100 mg', '1 cápsula cada 12 hrs con alimentos'),
('Profenid', 'Ketoprofeno', 'Cápsulas 200 mg liberación prolongada', '1 cápsula cada 24 hrs con alimentos'),
('Profenid', 'Ketoprofeno', 'Solución inyectable 100 mg/2 ml', '100 mg IM cada 12 hrs'),
('Ketoprofeno', 'Ketoprofeno', 'Cápsulas 50 mg', '1-2 cápsulas cada 8 hrs con alimentos'),
('Orudis', 'Ketoprofeno', 'Cápsulas 100 mg', '1 cápsula cada 12 hrs con alimentos'),
-- Ibuprofeno
('Motrin', 'Ibuprofeno', 'Tabletas 800 mg', '1 tableta cada 8 hrs con alimentos por 5-7 días'),
('Motrin', 'Ibuprofeno', 'Tabletas 400 mg', '1-2 tabletas cada 8 hrs con alimentos'),
('Advil', 'Ibuprofeno', 'Tabletas 400 mg', '1-2 tabletas cada 6-8 hrs con alimentos'),
('Ibuprofeno', 'Ibuprofeno', 'Tabletas 600 mg', '1 tableta cada 8 hrs con alimentos'),
('Ibuprofen', 'Ibuprofeno', 'Cápsulas blandas 400 mg', '1-2 cápsulas cada 8 hrs con alimentos'),
-- Naproxeno
('Flanax', 'Naproxeno sódico', 'Tabletas 550 mg', '1 tableta cada 12 hrs con alimentos'),
('Nalgesin', 'Naproxeno sódico', 'Tabletas 275 mg', '2 tabletas cada 12 hrs con alimentos'),
('Naprosyn', 'Naproxeno', 'Tabletas 500 mg', '1 tableta cada 12 hrs con alimentos'),
('Naproxeno', 'Naproxeno sódico', 'Tabletas 250 mg', '1-2 tabletas cada 8-12 hrs con alimentos'),
-- Meloxicam
('Mobic', 'Meloxicam', 'Tabletas 7.5 mg', '1-2 tabletas cada 24 hrs con alimentos'),
('Melox', 'Meloxicam', 'Tabletas 15 mg', '1 tableta cada 24 hrs con alimentos'),
('Meloxicam', 'Meloxicam', 'Tabletas 7.5 mg', '1-2 tabletas cada 24 hrs con alimentos'),
('Meloxicam', 'Meloxicam', 'Solución inyectable 15 mg/1.5 ml', '15 mg IM cada 24 hrs por 2-3 días'),
-- Ketorolaco
('Dolac', 'Ketorolaco trometamol', 'Tabletas 10 mg', '1 tableta cada 6-8 hrs por máximo 5 días'),
('Ketorolaco', 'Ketorolaco trometamol', 'Tabletas 10 mg', '1 tableta cada 6-8 hrs por máximo 5 días'),
('Dolac', 'Ketorolaco trometamol', 'Solución inyectable 30 mg/1 ml', '30 mg IM/IV cada 6-8 hrs, máx 5 días'),
('Ketorolaco', 'Ketorolaco trometamol', 'Solución inyectable 60 mg/2 ml', '30 mg IM/IV cada 6-8 hrs, máx 5 días'),
-- COX-2 selectivos
('Celebrex', 'Celecoxib', 'Cápsulas 100 mg', '2 cápsulas cada 12 hrs con alimentos'),
('Celebrex', 'Celecoxib', 'Cápsulas 200 mg', '1 cápsula cada 12-24 hrs con alimentos'),
('Arcoxia', 'Etoricoxib', 'Tabletas 60 mg', '1 tableta cada 24 hrs con alimentos'),
('Arcoxia', 'Etoricoxib', 'Tabletas 90 mg', '1 tableta cada 24 hrs con alimentos (máx 8 días en agudo)'),
('Arcoxia', 'Etoricoxib', 'Tabletas 120 mg', '1 tableta cada 24 hrs en gota aguda, máx 8 días'),
('Dynastat', 'Parecoxib', 'Polvo inyectable 40 mg', '40 mg IV/IM cada 12 hrs (dolor postquirúrgico)'),
('Prexige', 'Lumiracoxib', 'Tabletas 100 mg', '1-4 tabletas cada 24 hrs con alimentos'),
-- Otros AINEs
('Piroxicam', 'Piroxicam', 'Cápsulas 20 mg', '1 cápsula cada 24 hrs con alimentos'),
('Feldene', 'Piroxicam', 'Cápsulas 20 mg', '1 cápsula cada 24 hrs con alimentos'),
('Feldene Flash', 'Piroxicam', 'Tabletas dispersables 20 mg', '1 tableta cada 24 hrs (disolver en boca)'),
('Nimesulida', 'Nimesulida', 'Tabletas 100 mg', '1 tableta cada 12 hrs con alimentos por 7-10 días'),
('Aulin', 'Nimesulida', 'Sobres granulado 100 mg', '1 sobre disuelto en agua cada 12 hrs con alimentos'),
('Indocin', 'Indometacina', 'Cápsulas 25 mg', '1-2 cápsulas cada 8-12 hrs con alimentos'),
('Indometacina', 'Indometacina', 'Cápsulas 50 mg', '1 cápsula cada 8-12 hrs con alimentos'),
('Airtal', 'Aceclofenaco', 'Tabletas 100 mg', '1 tableta cada 12 hrs con alimentos'),
('Aceclofenaco', 'Aceclofenaco', 'Tabletas 100 mg', '1 tableta cada 12 hrs con alimentos'),
('Lornoxicam', 'Lornoxicam', 'Tabletas 8 mg', '1 tableta cada 8-12 hrs con alimentos'),
('Tenoxicam', 'Tenoxicam', 'Tabletas 20 mg', '1 tableta cada 24 hrs con alimentos'),
('Tilcotil', 'Tenoxicam', 'Tabletas 20 mg', '1 tableta cada 24 hrs con alimentos'),
('Acemetacina', 'Acemetacina', 'Cápsulas 60 mg', '1 cápsula cada 8 hrs con alimentos'),
('Rantudil', 'Acemetacina', 'Cápsulas 60 mg', '1 cápsula cada 8 hrs con alimentos'),
-- Paracetamol / Metamizol
('Tylenol', 'Paracetamol', 'Tabletas 500 mg', '1-2 tabletas cada 6-8 hrs, máx 8 tabletas/día'),
('Tempra', 'Paracetamol', 'Tabletas 500 mg', '1-2 tabletas cada 6-8 hrs, máx 8 tabletas/día'),
('Paracetamol', 'Paracetamol', 'Tabletas 1 g', '1 tableta cada 6-8 hrs, máx 4 g/día'),
('Nolotil', 'Metamizol sódico', 'Cápsulas 575 mg', '1-2 cápsulas cada 6-8 hrs'),
('Dipirona', 'Metamizol sódico', 'Tabletas 500 mg', '1-2 tabletas cada 6-8 hrs'),
('Metamizol', 'Metamizol sódico', 'Solución inyectable 1 g/2 ml', '1-2 g IM/IV cada 6-8 hrs según dolor'),
('Buscapina Compositum', 'Butilescopolamina / Metamizol', 'Tabletas 10/500 mg', '1-2 tabletas cada 8 hrs'),
('Buscapina Compositum N', 'Butilescopolamina / Metamizol', 'Solución inyectable 20/2500 mg/5 ml', '1 ampolleta IM cada 8 hrs'),
-- ── RELAJANTES MUSCULARES ───────────────────────────────────
('Flexeril', 'Ciclobenzaprina', 'Tabletas 10 mg', '1 tableta cada 8 hrs (preferentemente noche)'),
('Ciclobenzaprina', 'Ciclobenzaprina', 'Tabletas 5 mg', '1 tableta cada 8 hrs'),
('Robaxin', 'Metocarbamol', 'Tabletas 750 mg', '2 tabletas cada 8 hrs los primeros 2-3 días, luego 1 tableta cada 8 hrs'),
('Metocarbamol', 'Metocarbamol', 'Tabletas 500 mg', '2 tabletas cada 8 hrs'),
('Soma', 'Carisoprodol', 'Tabletas 350 mg', '1 tableta cada 8 hrs y al acostarse'),
('Carisoprodol', 'Carisoprodol', 'Tabletas 350 mg', '1 tableta cada 8 hrs y al acostarse'),
('Mydocalm', 'Tolperisona', 'Tabletas 150 mg', '1 tableta cada 8 hrs con alimentos'),
('Tolperisona', 'Tolperisona', 'Tabletas 100 mg', '1-2 tabletas cada 8 hrs con alimentos'),
('Lioresal', 'Baclofeno', 'Tabletas 10 mg', '1 tableta cada 8 hrs, aumentar gradualmente cada 3 días'),
('Baclofeno', 'Baclofeno', 'Tabletas 25 mg', '1 tableta cada 8-12 hrs, ajustar según respuesta'),
('Sibaril', 'Tizanidina', 'Tabletas 2 mg', '1-2 tabletas cada 8 hrs'),
('Tizanidina', 'Tizanidina', 'Tabletas 4 mg', '1 tableta cada 8-12 hrs'),
('Orfenadrina', 'Orfenadrina', 'Tabletas 100 mg', '1 tableta cada 12 hrs'),
('Norflex', 'Orfenadrina', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 12 hrs'),
('Norflex', 'Orfenadrina', 'Solución inyectable 60 mg/2 ml', '60 mg IM/IV cada 12 hrs'),
('Dantrium', 'Dantroleno', 'Cápsulas 25 mg', '1 cápsula cada 8 hrs, aumentar gradualmente hasta 100 mg cada 8 hrs'),
('Valium', 'Diazepam', 'Tabletas 5 mg', '1 tableta cada 8-12 hrs (espasmo muscular agudo)'),
('Diazepam', 'Diazepam', 'Tabletas 10 mg', '½-1 tableta cada 8-12 hrs'),
('Muscoril', 'Tiocolchicósido', 'Cápsulas 4 mg', '1 cápsula cada 12 hrs por máximo 7 días'),
('Tiocolchicósido', 'Tiocolchicósido', 'Solución inyectable 4 mg/2 ml', '4-8 mg IM cada 12 hrs por máximo 5 días'),
('Lumirelax', 'Methocarbamol + Ibuprofeno', 'Tabletas 400/200 mg', '1 tableta cada 8 hrs con alimentos'),
('Yurelax', 'Ciclobenzaprina + Diclofenaco', 'Tabletas 5/50 mg', '1 tableta cada 8 hrs con alimentos'),
-- ── OPIOIDES / ANALGÉSICOS FUERTES ─────────────────────────
('Tramal', 'Tramadol', 'Cápsulas 50 mg', '1-2 cápsulas cada 6-8 hrs, máx 400 mg/día'),
('Tramadol', 'Tramadol', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 12-24 hrs, máx 400 mg/día'),
('Tramal Long', 'Tramadol', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 12-24 hrs'),
('Tramal', 'Tramadol', 'Solución inyectable 100 mg/2 ml', '100 mg IV/IM cada 6-8 hrs, diluir en SF'),
('Tramacet', 'Tramadol / Paracetamol', 'Tabletas 37.5/325 mg', '1-2 tabletas cada 6-8 hrs, máx 8 tabletas/día'),
('Zaldiar', 'Tramadol / Paracetamol', 'Tabletas 37.5/325 mg', '1-2 tabletas cada 6-8 hrs, máx 8 tabletas/día'),
('Tapentadol', 'Tapentadol', 'Tabletas 50 mg', '1 tableta cada 4-6 hrs según dolor, máx 500 mg/día'),
('Nucynta', 'Tapentadol', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 12 hrs, ajustar según respuesta'),
('Palexia', 'Tapentadol', 'Tabletas 50 mg', '1 tableta cada 4-6 hrs, máx 500 mg/día'),
('Palexia Retard', 'Tapentadol', 'Tabletas 100 mg liberación prolongada', '1 tableta cada 12 hrs'),
('Codeína', 'Codeína fosfato', 'Tabletas 30 mg', '1 tableta cada 4-6 hrs según necesidad'),
('Codeína', 'Codeína fosfato', 'Tabletas 60 mg', '1 tableta cada 6-8 hrs según necesidad'),
('Tylex', 'Paracetamol / Codeína', 'Cápsulas 500/30 mg', '1-2 cápsulas cada 4-6 hrs, máx 8 cápsulas/día'),
('Morfina', 'Sulfato de morfina', 'Tabletas 10 mg liberación inmediata', '5-15 mg cada 4 hrs, ajustar según respuesta'),
('Morfina LP', 'Sulfato de morfina', 'Tabletas 30 mg liberación prolongada', '1 tableta cada 12 hrs (no masticar)'),
('MST Continus', 'Sulfato de morfina', 'Tabletas 15 mg liberación prolongada', '1 tableta cada 12 hrs'),
('Morfina', 'Cloruro de morfina', 'Solución inyectable 10 mg/1 ml', '5-10 mg SC/IM cada 4 hrs, titular según dolor'),
('OxyContin', 'Oxicodona', 'Tabletas 10 mg liberación prolongada', '1 tableta cada 12 hrs (no masticar)'),
('OxyContin', 'Oxicodona', 'Tabletas 20 mg liberación prolongada', '1 tableta cada 12 hrs'),
('OxyContin', 'Oxicodona', 'Tabletas 40 mg liberación prolongada', '1 tableta cada 12 hrs'),
('Oxynorm', 'Oxicodona', 'Cápsulas 5 mg liberación inmediata', '1-2 cápsulas cada 4-6 hrs (rescate)'),
('Targinact', 'Oxicodona / Naloxona', 'Tabletas 10/5 mg liberación prolongada', '1 tableta cada 12 hrs'),
('Durogesic', 'Fentanilo transdérmico', 'Parche 12 mcg/hr', '1 parche cada 72 hrs (iniciar en opioides ingenuos)'),
('Durogesic', 'Fentanilo transdérmico', 'Parche 25 mcg/hr', '1 parche cada 72 hrs'),
('Durogesic', 'Fentanilo transdérmico', 'Parche 50 mcg/hr', '1 parche cada 72 hrs'),
('Durogesic', 'Fentanilo transdérmico', 'Parche 75 mcg/hr', '1 parche cada 72 hrs'),
('Fentanilo', 'Fentanilo', 'Solución inyectable 0.05 mg/1 ml', '0.5-1 mcg/kg IV lento, titular según dolor'),
('Abstral', 'Fentanilo', 'Tabletas sublinguales 100 mcg', '100-800 mcg sublingual (rescate en dolor irruptivo)'),
('Actiq', 'Fentanilo citrato', 'Aplicador bucal 200 mcg', '200-1600 mcg transmucoso (dolor irruptivo)'),
('Norspan', 'Buprenorfina transdérmica', 'Parche 5 mcg/hr', '1 parche cada 7 días (cambiar el mismo día de la semana)'),
('Norspan', 'Buprenorfina transdérmica', 'Parche 10 mcg/hr', '1 parche cada 7 días'),
('Norspan', 'Buprenorfina transdérmica', 'Parche 20 mcg/hr', '1 parche cada 7 días'),
('Transtec', 'Buprenorfina transdérmica', 'Parche 35 mcg/hr', '1 parche cada 4 días (96 hrs)'),
('Hidromorfona', 'Hidromorfona', 'Tabletas 2 mg liberación inmediata', '1-2 tabletas cada 4-6 hrs, ajustar según respuesta'),
('Palladone', 'Hidromorfona', 'Cápsulas 4 mg', '1 cápsula cada 4-6 hrs'),
('Nubain', 'Nalbufina', 'Solución inyectable 10 mg/1 ml', '10-20 mg IM/IV/SC cada 3-6 hrs según dolor'),
('Metadona', 'Metadona', 'Tabletas 5 mg', 'Dosis individualizada, iniciar 2.5-5 mg cada 8-12 hrs (especialista)'),
('Meperidina', 'Meperidina (Petidina)', 'Solución inyectable 100 mg/2 ml', '50-100 mg IM cada 3-4 hrs (uso hospitalario)'),
('Dolantina', 'Meperidina', 'Solución inyectable 100 mg/2 ml', '50-100 mg IM cada 3-4 hrs'),
('Naloxona', 'Naloxona', 'Solución inyectable 0.4 mg/1 ml', '0.4-2 mg IV/IM (reversión de opioides, repetir cada 2-3 min)'),
-- ── NEUROPÁTICOS / DOLOR CRÓNICO ───────────────────────────
('Lyrica', 'Pregabalina', 'Cápsulas 25 mg', '1 cápsula cada 8-12 hrs (dosis inicial)'),
('Lyrica', 'Pregabalina', 'Cápsulas 75 mg', '1 cápsula cada 12 hrs, puede aumentarse a 150 mg c/12 hrs'),
('Lyrica', 'Pregabalina', 'Cápsulas 150 mg', '1 cápsula cada 12 hrs'),
('Lyrica', 'Pregabalina', 'Cápsulas 300 mg', '1 cápsula cada 12 hrs (dosis máxima 600 mg/día)'),
('Lyrica CR', 'Pregabalina', 'Tabletas 165 mg liberación prolongada', '1 tableta cada 24 hrs con alimentos'),
('Lyrica CR', 'Pregabalina', 'Tabletas 330 mg liberación prolongada', '1 tableta cada 24 hrs con alimentos'),
('Pregabalina', 'Pregabalina', 'Cápsulas 50 mg', '1 cápsula cada 8 hrs'),
('Neurontin', 'Gabapentina', 'Cápsulas 100 mg', '1 cápsula cada 8 hrs (titulación inicial)'),
('Neurontin', 'Gabapentina', 'Cápsulas 300 mg', '1 cápsula cada 8 hrs, aumentar gradualmente'),
('Neurontin', 'Gabapentina', 'Cápsulas 400 mg', '1 cápsula cada 8 hrs'),
('Gabapentina', 'Gabapentina', 'Cápsulas 600 mg', '1 cápsula cada 8-12 hrs (máx 3600 mg/día)'),
('Gabapentina', 'Gabapentina', 'Cápsulas 800 mg', '1 cápsula cada 8 hrs'),
('Horizant', 'Gabapentina enacarbil', 'Tabletas 300 mg liberación prolongada', '1-2 tabletas cada 24 hrs con alimentos'),
('Cymbalta', 'Duloxetina', 'Cápsulas 30 mg', '1 cápsula cada 24 hrs (dosis inicial)'),
('Cymbalta', 'Duloxetina', 'Cápsulas 60 mg', '1 cápsula cada 24 hrs con alimentos'),
('Duloxetina', 'Duloxetina', 'Cápsulas 90 mg', '1 cápsula cada 24 hrs (máx 120 mg/día)'),
('Amitriptilina', 'Amitriptilina', 'Tabletas 10 mg', '1-3 tabletas en la noche al acostarse (iniciar con 10 mg)'),
('Tryptizol', 'Amitriptilina', 'Tabletas 25 mg', '1 tableta en la noche al acostarse'),
('Amitriptilina', 'Amitriptilina', 'Tabletas 75 mg', '1 tableta en la noche al acostarse'),
('Nortriptilina', 'Nortriptilina', 'Cápsulas 25 mg', '1-3 cápsulas en la noche al acostarse'),
('Pamelor', 'Nortriptilina', 'Cápsulas 10 mg', '1-3 cápsulas en la noche al acostarse'),
('Tegretol', 'Carbamazepina', 'Tabletas 200 mg', '1 tableta cada 12 hrs, aumentar gradualmente según respuesta'),
('Carbamazepina', 'Carbamazepina', 'Tabletas 400 mg', '1 tableta cada 12 hrs'),
('Tegretol CR', 'Carbamazepina', 'Tabletas 400 mg liberación prolongada', '1 tableta cada 12-24 hrs'),
('Oxcarbazepina', 'Oxcarbazepina', 'Tabletas 300 mg', '1 tableta cada 12 hrs, aumentar 300 mg/semana según respuesta'),
('Trileptal', 'Oxcarbazepina', 'Tabletas 600 mg', '1 tableta cada 12 hrs'),
('Versatis', 'Lidocaína', 'Parche 5% (700 mg)', '1-3 parches en zona afectada 12 hrs con parche / 12 hrs sin parche'),
('Lidoderm', 'Lidocaína', 'Parche 5% (700 mg)', '1-3 parches en zona afectada 12 hrs / 12 hrs'),
('Zostrix', 'Capsaicina', 'Crema 0.025%', 'Aplicar 3-4 veces al día en zona afectada (puede arder al inicio)'),
('Zostrix HP', 'Capsaicina', 'Crema 0.075%', 'Aplicar 3-4 veces al día en zona afectada'),
('Qutenza', 'Capsaicina', 'Parche 8% (179 mg)', 'Aplicación única por 30-60 min (uso hospitalario especializado)'),
('Rivotril', 'Clonazepam', 'Tabletas 0.5 mg', '1 tableta cada 12 hrs o en la noche (dolor neuropático)'),
('Rivotril', 'Clonazepam', 'Tabletas 2 mg', '½-1 tableta en la noche'),
('Neurobión Forte', 'Vitaminas B1 / B6 / B12', 'Tabletas 100/200/200 mcg', '1 tableta cada 24 hrs (neuropatía periférica)'),
('Neurobión', 'Vitaminas B1 / B6 / B12', 'Solución inyectable 3 ml', '1 ampolleta IM cada 24 hrs por 10-14 días'),
('Vitamina B12', 'Cianocobalamina', 'Tabletas 1000 mcg', '1 tableta cada 24 hrs (neuropatía por deficiencia)'),
('Metilcobalamina', 'Metilcobalamina', 'Cápsulas 1000 mcg', '1 cápsula cada 24 hrs'),
('Ácido alfa-lipoico', 'Ácido alfa-lipoico', 'Tabletas 600 mg', '1 tableta cada 24 hrs en ayunas (neuropatía diabética)'),
('Thioctacid', 'Ácido alfa-lipoico', 'Tabletas 600 mg', '1 tableta cada 24 hrs en ayunas'),
('Topamax', 'Topiramato', 'Tabletas 25 mg', 'Iniciar 25 mg/noche, aumentar 25 mg cada semana según respuesta'),
('Topiramato', 'Topiramato', 'Tabletas 100 mg', '1 tableta cada 12 hrs'),
('Venlafaxina', 'Venlafaxina', 'Cápsulas 75 mg liberación prolongada', '1 cápsula cada 24 hrs con alimentos (dolor neuropático)'),
('Effexor XR', 'Venlafaxina', 'Cápsulas 150 mg liberación prolongada', '1 cápsula cada 24 hrs con alimentos'),
-- ── CORTICOSTEROIDES ────────────────────────────────────────
('Prednisona', 'Prednisona', 'Tabletas 5 mg', '1-4 tabletas cada 24 hrs con alimentos (esquema decreciente)'),
('Prednisona', 'Prednisona', 'Tabletas 20 mg', '1 tableta cada 24 hrs con alimentos'),
('Prednisona', 'Prednisona', 'Tabletas 50 mg', '1 tableta cada 24 hrs con alimentos'),
('Medrol', 'Metilprednisolona', 'Tabletas 4 mg', 'Según Dosepack: esquema decreciente 8 días'),
('Medrol', 'Metilprednisolona', 'Tabletas 16 mg', '1 tableta cada 24 hrs con alimentos'),
('Solu-Medrol', 'Metilprednisolona', 'Polvo inyectable 40 mg', '40-125 mg IV/IM según indicación'),
('Solu-Medrol', 'Metilprednisolona', 'Polvo inyectable 125 mg', '125-1000 mg IV según indicación (pulsos)'),
('Decadrón', 'Dexametasona', 'Tabletas 0.75 mg', '2-4 tabletas cada 24 hrs con alimentos'),
('Dexametasona', 'Dexametasona', 'Tabletas 1.5 mg', '1-2 tabletas cada 24 hrs con alimentos'),
('Dexametasona', 'Dexametasona', 'Solución inyectable 4 mg/1 ml', '4-8 mg IM/IV cada 8-24 hrs según indicación'),
('Dexametasona', 'Dexametasona', 'Solución inyectable 8 mg/2 ml', '4-8 mg IM/IV según indicación'),
('Celestone', 'Betametasona', 'Tabletas 0.5 mg', '1-4 tabletas cada 24 hrs con alimentos'),
('Deflazacort', 'Deflazacort', 'Tabletas 6 mg', '1-2 tabletas cada 24 hrs con alimentos'),
('Calcort', 'Deflazacort', 'Tabletas 30 mg', '1 tableta cada 24 hrs con alimentos'),
('Hidrocortisona', 'Hidrocortisona', 'Tabletas 20 mg', '10-20 mg en la mañana y 5-10 mg en la tarde'),
('Solu-Cortef', 'Hidrocortisona', 'Polvo inyectable 100 mg', '100-500 mg IV según indicación'),
-- ── INFILTRACIONES / ANESTÉSICOS LOCALES ───────────────────
('Lidocaína', 'Lidocaína clorhidrato', 'Solución inyectable 1% 50 ml', 'Infiltración local: 1-10 ml según zona (máx 4.5 mg/kg)'),
('Xylocaína', 'Lidocaína clorhidrato', 'Solución inyectable 2% 20 ml', 'Bloqueo / infiltración: 1-5 ml según zona'),
('Lidocaína con epinefrina', 'Lidocaína / Epinefrina', 'Solución inyectable 2% 1:100,000', 'Infiltración local: 1-5 ml (no usar en dedos, nariz, pene, orejas)'),
('Marcaína', 'Bupivacaína', 'Solución inyectable 0.25% 20 ml', 'Bloqueo nervioso: 10-20 ml según técnica'),
('Marcaína', 'Bupivacaína', 'Solución inyectable 0.5% 20 ml', 'Bloqueo nervioso: 5-20 ml según técnica (máx 2.5 mg/kg)'),
('Naropin', 'Ropivacaína', 'Solución inyectable 0.2% 200 ml', 'Infusión continua: 6-14 ml/hr para analgesia epidural'),
('Naropin', 'Ropivacaína', 'Solución inyectable 0.75% 20 ml', 'Bloqueo nervioso: 10-30 ml según técnica'),
('Mepivacaína', 'Mepivacaína', 'Solución inyectable 1% 20 ml', 'Infiltración: 1-10 ml según zona'),
('Mepivacaína', 'Mepivacaína', 'Solución inyectable 2% 20 ml', 'Bloqueo: 5-20 ml según técnica (máx 5-6 mg/kg)'),
('Kenacort-A', 'Triamcinolona acetónida', 'Suspensión inyectable 40 mg/1 ml', 'IA grande (rodilla, hombro): 20-40 mg; IA pequeña: 5-10 mg'),
('Triamcinolona', 'Triamcinolona acetónida', 'Suspensión inyectable 10 mg/1 ml', 'IA pequeña: 5-10 mg; peritendinosa: 5-20 mg'),
('Depo-Medrol', 'Metilprednisolona acetato', 'Suspensión inyectable 40 mg/1 ml', 'IA grande: 40-80 mg; IA pequeña: 20-40 mg; bursa: 20-40 mg'),
('Depo-Medrol', 'Metilprednisolona acetato', 'Suspensión inyectable 80 mg/2 ml', 'IA grande: 40-80 mg'),
('Diprophos', 'Betametasona dipropionato / fosfato sódico', 'Suspensión inyectable 7 mg/1 ml', 'IA grande: 1-2 ml; IA pequeña: 0.25-0.5 ml; bursa: 1-2 ml'),
('Celestone Soluspan', 'Betametasona dipropionato / fosfato sódico', 'Suspensión inyectable 6 mg/1 ml', 'IA: 0.5-2 ml según articulación'),
('Ostenil', 'Hialuronato de sodio', 'Jeringa precargada 20 mg/2 ml', '1 inyección IA semanal por 3-5 semanas'),
('Ostenil Plus', 'Hialuronato de sodio', 'Jeringa precargada 40 mg/2 ml', '1 inyección IA única o 1 semanal por 3 semanas'),
('Synvisc', 'Hylan G-F 20', 'Jeringa precargada 16 mg/2 ml', '1 inyección IA semanal por 3 semanas'),
('Synvisc-One', 'Hylan G-F 20', 'Jeringa precargada 48 mg/6 ml', '1 inyección IA única'),
('Durolane', 'Hialuronato de sodio estabilizado', 'Jeringa precargada 60 mg/3 ml', '1 inyección IA única'),
('Supartz', 'Hialuronato de sodio', 'Jeringa precargada 25 mg/2.5 ml', '1 inyección IA semanal por 5 semanas'),
('Euflexxa', 'Hialuronato de sodio', 'Jeringa precargada 20 mg/2 ml', '1 inyección IA semanal por 3 semanas'),
('PRP Autólogo', 'Plasma Rico en Plaquetas', 'Preparación autóloga variable', 'Infiltración IA o peritendinosa, 1-3 ml según protocolo, 1-3 sesiones'),
-- Tópicos ortopédicos
('Voltaren Emulgel', 'Diclofenaco dietilamonio', 'Gel 1% 100 g', 'Aplicar 2-4 g en zona afectada cada 8-12 hrs, máx 3 semanas'),
('Voltaren Emulgel Forte', 'Diclofenaco dietilamonio', 'Gel 2% 100 g', 'Aplicar 2-4 g en zona afectada cada 12 hrs'),
('Flector Parche', 'Diclofenaco epolamina', 'Parche 140 mg', '1 parche en zona afectada cada 12 hrs, máx 3 semanas'),
('Diclofenaco Parche', 'Diclofenaco sódico', 'Parche 140 mg', '1 parche en zona afectada cada 12 hrs'),
('Ketoprofeno Gel', 'Ketoprofeno', 'Gel 2.5% 60 g', 'Aplicar 2-3 g en zona afectada cada 8-12 hrs'),
('Ibuprofeno Gel', 'Ibuprofeno', 'Gel 5% 60 g', 'Aplicar 4-10 cm de gel en zona afectada cada 8 hrs'),
('Piroxicam Gel', 'Piroxicam', 'Gel 0.5% 60 g', 'Aplicar 1-2 g en zona afectada cada 8-12 hrs'),
('Nimesulida Gel', 'Nimesulida', 'Gel 3% 30 g', 'Aplicar 3 cm de gel en zona afectada cada 12 hrs'),
('Traumeel Gel', 'Complejo homeopático antiinflamatorio', 'Gel 50 g', 'Aplicar en zona afectada 2-3 veces al día'),
('Capsicina Crema', 'Capsaicina', 'Crema 0.025%', 'Aplicar 3-4 veces al día en zona afectada (puede arder al inicio)'),
-- ── GASTROPROTECTORES ───────────────────────────────────────
('Omeprazol', 'Omeprazol', 'Cápsulas 20 mg', '1 cápsula cada 24 hrs en ayunas, 30 min antes del desayuno'),
('Omeprazol', 'Omeprazol', 'Cápsulas 40 mg', '1 cápsula cada 24 hrs en ayunas'),
('Prilosec', 'Omeprazol', 'Cápsulas 20 mg', '1 cápsula cada 24 hrs en ayunas'),
('Pantoprazol', 'Pantoprazol', 'Tabletas 40 mg', '1 tableta cada 24 hrs en ayunas'),
('Protonix', 'Pantoprazol', 'Tabletas 40 mg', '1 tableta cada 24 hrs en ayunas'),
('Nexium', 'Esomeprazol', 'Cápsulas 40 mg', '1 cápsula cada 24 hrs en ayunas'),
('Esomeprazol', 'Esomeprazol', 'Cápsulas 20 mg', '1 cápsula cada 24 hrs en ayunas'),
('Prevacid', 'Lansoprazol', 'Cápsulas 30 mg', '1 cápsula cada 24 hrs en ayunas'),
('Rabeprazol', 'Rabeprazol', 'Tabletas 20 mg', '1 tableta cada 24 hrs en ayunas'),
('Ulsen', 'Sucralfato', 'Tabletas 1 g', '1 tableta cada 8 hrs en ayunas, 1 hr antes de alimentos'),
('Misoprostol', 'Misoprostol', 'Tabletas 200 mcg', '1 tableta cada 6-8 hrs con alimentos (protección gástrica con AINEs)'),
('Cytotec', 'Misoprostol', 'Tabletas 200 mcg', '1 tableta cada 6-8 hrs con alimentos'),
-- ── ANTIBIÓTICOS ────────────────────────────────────────────
-- Penicilinas
('Amoxil', 'Amoxicilina', 'Cápsulas 500 mg', '1 cápsula cada 8 hrs por 7-10 días'),
('Amoxicilina', 'Amoxicilina', 'Cápsulas 250 mg', '1-2 cápsulas cada 8 hrs por 7-10 días'),
('Amoxicilina', 'Amoxicilina', 'Tabletas 1 g', '1 tableta cada 12 hrs por 7-10 días'),
('Augmentin', 'Amoxicilina / Ácido clavulánico', 'Tabletas 875/125 mg', '1 tableta cada 12 hrs con alimentos por 7-10 días'),
('Amoclave', 'Amoxicilina / Ácido clavulánico', 'Tabletas 500/125 mg', '1 tableta cada 8 hrs con alimentos por 7-10 días'),
('Clavulin', 'Amoxicilina / Ácido clavulánico', 'Tabletas 875/125 mg', '1 tableta cada 12 hrs con alimentos por 7-10 días'),
('Ampicilina', 'Ampicilina', 'Cápsulas 500 mg', '1 cápsula cada 6 hrs en ayunas por 7-10 días'),
('Dicloxacilina', 'Dicloxacilina', 'Cápsulas 500 mg', '1 cápsula cada 6 hrs en ayunas por 7-10 días (infecciones estafilocócicas)'),
('Dicloxacilina', 'Dicloxacilina', 'Cápsulas 250 mg', '1-2 cápsulas cada 6 hrs en ayunas'),
('Unasyn oral', 'Ampicilina / Sulbactam', 'Tabletas 375 mg', '1 tableta cada 8 hrs con alimentos por 7-10 días'),
('Piperacilina/Tazobactam', 'Piperacilina / Tazobactam', 'Polvo inyectable 4.5 g', '4.5 g IV cada 6-8 hrs (uso hospitalario)'),
('Tazocin', 'Piperacilina / Tazobactam', 'Polvo inyectable 2.25 g', '2.25-4.5 g IV cada 6-8 hrs (uso hospitalario)'),
-- Cefalosporinas
('Keflex', 'Cefalexina', 'Cápsulas 500 mg', '1-2 cápsulas cada 6 hrs por 7-10 días'),
('Cefalexina', 'Cefalexina', 'Cápsulas 250 mg', '1-2 cápsulas cada 6 hrs'),
('Duracef', 'Cefadroxilo', 'Cápsulas 500 mg', '1 cápsula cada 12 hrs por 7-10 días'),
('Cefadroxil', 'Cefadroxilo', 'Cápsulas 1 g', '1 cápsula cada 24 hrs por 7-10 días'),
('Cefalotina', 'Cefalotina', 'Polvo inyectable 1 g', '1-2 g IV/IM cada 6 hrs (profilaxis quirúrgica / tratamiento)'),
('Zinnat', 'Cefuroxima', 'Tabletas 500 mg', '1 tableta cada 12 hrs con alimentos por 7-10 días'),
('Cefuroxima', 'Cefuroxima', 'Polvo inyectable 750 mg', '750 mg IM/IV cada 8 hrs'),
('Cefaclor', 'Cefaclor', 'Cápsulas 500 mg', '1 cápsula cada 8 hrs por 7-10 días'),
('Suprax', 'Cefixima', 'Tabletas 400 mg', '1 tableta cada 24 hrs por 7-14 días'),
('Cefixima', 'Cefixima', 'Tabletas 200 mg', '1 tableta cada 12 hrs por 7-14 días'),
('Omnicef', 'Cefdinir', 'Cápsulas 300 mg', '1 cápsula cada 12 hrs por 7-10 días'),
('Rocephin', 'Ceftriaxona', 'Polvo inyectable 1 g', '1-2 g IV/IM cada 24 hrs (uso hospitalario/ambulatorio)'),
('Ceftriaxona', 'Ceftriaxona', 'Polvo inyectable 500 mg', '500 mg-1 g IM cada 24 hrs'),
('Cefotaxima', 'Cefotaxima', 'Polvo inyectable 1 g', '1-2 g IV cada 8-12 hrs (uso hospitalario)'),
('Ceftazidima', 'Ceftazidima', 'Polvo inyectable 1 g', '1-2 g IV cada 8-12 hrs (Pseudomonas)'),
('Cefepima', 'Cefepima', 'Polvo inyectable 1 g', '1-2 g IV cada 8-12 hrs (4ª generación)'),
('Ceftarolina', 'Ceftarolina fosamil', 'Polvo inyectable 600 mg', '600 mg IV cada 12 hrs (SARM)'),
-- Carbapenems
('Primaxin', 'Imipenem / Cilastatina', 'Polvo inyectable 500 mg', '500 mg IV cada 6-8 hrs (uso hospitalario)'),
('Imipenem', 'Imipenem / Cilastatina', 'Polvo inyectable 1 g', '500 mg-1 g IV cada 6-8 hrs'),
('Merrem', 'Meropenem', 'Polvo inyectable 1 g', '1-2 g IV cada 8 hrs (uso hospitalario)'),
('Meropenem', 'Meropenem', 'Polvo inyectable 500 mg', '500 mg-1 g IV cada 8 hrs'),
('Invanz', 'Ertapenem', 'Polvo inyectable 1 g', '1 g IV/IM cada 24 hrs (uso ambulatorio/hospitalario)'),
('Ertapenem', 'Ertapenem', 'Polvo inyectable 1 g', '1 g IV/IM cada 24 hrs'),
-- Macrólidos
('Zithromax', 'Azitromicina', 'Tabletas 500 mg', '1 tableta cada 24 hrs por 3-5 días'),
('Azitromicina', 'Azitromicina', 'Tabletas 250 mg', '2 tabletas el día 1, luego 1 tableta cada 24 hrs por 4 días'),
('Klaricid', 'Claritromicina', 'Tabletas 500 mg', '1 tableta cada 12 hrs por 7-14 días'),
('Claritromicina', 'Claritromicina', 'Tabletas 250 mg', '1 tableta cada 12 hrs por 7-14 días'),
('Klaricid XL', 'Claritromicina', 'Tabletas 500 mg liberación prolongada', '1-2 tabletas cada 24 hrs con alimentos'),
('Eritromicina', 'Eritromicina etilsuccinato', 'Tabletas 500 mg', '1 tableta cada 6-8 hrs con alimentos por 7-10 días'),
-- Quinolonas
('Ciprobay', 'Ciprofloxacino', 'Tabletas 500 mg', '1 tableta cada 12 hrs por 7-14 días'),
('Ciprofloxacino', 'Ciprofloxacino', 'Tabletas 750 mg', '1 tableta cada 12 hrs por 7-14 días (infecciones óseas)'),
('Ciprofloxacino', 'Ciprofloxacino', 'Solución inyectable 200 mg/100 ml', '200-400 mg IV cada 12 hrs'),
('Tavanic', 'Levofloxacino', 'Tabletas 500 mg', '1 tableta cada 24 hrs por 7-14 días'),
('Levofloxacino', 'Levofloxacino', 'Tabletas 750 mg', '1 tableta cada 24 hrs por 5-7 días'),
('Levofloxacino', 'Levofloxacino', 'Solución inyectable 500 mg/100 ml', '500-750 mg IV cada 24 hrs'),
('Avelox', 'Moxifloxacino', 'Tabletas 400 mg', '1 tableta cada 24 hrs por 5-10 días'),
('Moxifloxacino', 'Moxifloxacino', 'Solución inyectable 400 mg/250 ml', '400 mg IV cada 24 hrs'),
('Norfloxacino', 'Norfloxacino', 'Tabletas 400 mg', '1 tableta cada 12 hrs en ayunas por 7-10 días'),
('Ofloxacino', 'Ofloxacino', 'Tabletas 400 mg', '1 tableta cada 12 hrs por 7-14 días'),
('Delafloxacino', 'Delafloxacino', 'Tabletas 450 mg', '1 tableta cada 12 hrs por 5-14 días (SARM-susceptible)'),
-- Tetraciclinas
('Vibramycin', 'Doxiciclina', 'Cápsulas 100 mg', '1 cápsula cada 12 hrs con alimentos por 7-14 días'),
('Doxiciclina', 'Doxiciclina', 'Tabletas 100 mg', '1 tableta cada 12 hrs con alimentos por 7-14 días'),
('Minociclina', 'Minociclina', 'Cápsulas 100 mg', '1 cápsula cada 12 hrs con alimentos'),
('Minocin', 'Minociclina', 'Cápsulas 50 mg', '1-2 cápsulas cada 12 hrs con alimentos'),
-- Aminoglucósidos
('Gentamicina', 'Gentamicina', 'Solución inyectable 80 mg/2 ml', '3-5 mg/kg/día IM/IV en 1-3 dosis (monitorizar función renal)'),
('Amikacina', 'Amikacina', 'Solución inyectable 500 mg/2 ml', '15-20 mg/kg/día IM/IV (monitorizar niveles)'),
('Tobramicina', 'Tobramicina', 'Solución inyectable 80 mg/2 ml', '3-5 mg/kg/día IM/IV en 1-3 dosis'),
-- Lincosamidas
('Dalacin C', 'Clindamicina', 'Cápsulas 300 mg', '1 cápsula cada 8 hrs por 7-10 días'),
('Clindamicina', 'Clindamicina', 'Cápsulas 150 mg', '1-2 cápsulas cada 6-8 hrs'),
('Dalacin C', 'Clindamicina', 'Solución inyectable 300 mg/2 ml', '600-900 mg IV cada 8 hrs (infecciones óseas/articulares graves)'),
('Clindamicina', 'Clindamicina', 'Solución inyectable 600 mg/4 ml', '600-900 mg IV cada 8 hrs'),
-- Nitroimidazoles
('Flagyl', 'Metronidazol', 'Tabletas 500 mg', '1 tableta cada 8 hrs por 7-10 días (infecciones anaerobias)'),
('Metronidazol', 'Metronidazol', 'Solución inyectable 500 mg/100 ml', '500 mg IV cada 8 hrs (uso hospitalario)'),
('Tinidazol', 'Tinidazol', 'Tabletas 500 mg', '2 g dosis única o 1 g cada 12 hrs por 5 días'),
-- Glicopéptidos
('Vancocin', 'Vancomicina', 'Polvo inyectable 500 mg', '15-20 mg/kg IV cada 8-12 hrs (SARM, uso hospitalario)'),
('Vancomicina', 'Vancomicina', 'Polvo inyectable 1 g', '1 g IV cada 12 hrs (ajustar según niveles)'),
('Teicoplanina', 'Teicoplanina', 'Polvo inyectable 400 mg', 'Carga: 400 mg IV/IM cada 12 hrs × 3; mantenimiento: 400 mg/día'),
-- Sulfonamidas
('Bactrim', 'Trimetoprim / Sulfametoxazol', 'Tabletas 160/800 mg', '1 tableta cada 12 hrs por 7-10 días'),
('Bactrim F', 'Trimetoprim / Sulfametoxazol', 'Tabletas 160/800 mg', '1 tableta cada 12 hrs'),
-- Oxazolidinonas / Otros
('Zyvox', 'Linezolid', 'Tabletas 600 mg', '1 tableta cada 12 hrs por 10-14 días (SARM)'),
('Linezolid', 'Linezolid', 'Solución inyectable 600 mg/300 ml', '600 mg IV cada 12 hrs'),
('Sivextro', 'Tedizolid', 'Tabletas 200 mg', '1 tableta cada 24 hrs por 6 días (infecciones de piel y tejidos blandos)'),
('Cubicin', 'Daptomicina', 'Polvo inyectable 500 mg', '4-6 mg/kg IV cada 24 hrs (infecciones por SARM)'),
('Rifampicina', 'Rifampicina', 'Cápsulas 300 mg', '600 mg/día en 2 dosis en ayunas (osteomielitis, combinada)'),
('Fosfomicina', 'Fosfomicina trometamol', 'Sobres 3 g', '1 sobre disuelto en agua dosis única (IVU no complicada)'),
('Monurol', 'Fosfomicina trometamol', 'Sobres 3 g', '1 sobre disuelto en agua dosis única'),
('Tigeciclina', 'Tigeciclina', 'Polvo inyectable 50 mg', '100 mg IV dosis inicial, luego 50 mg cada 12 hrs'),
('Colistina', 'Colistimetato sódico', 'Polvo inyectable 150 mg', 'Según peso y función renal (gramnegativos multirresistentes)'),
-- ── ANTIOSTEOPOROSIS / METABOLISMO ÓSEO ────────────────────
-- Bisfosfonatos
('Fosamax', 'Alendronato sódico', 'Tabletas 70 mg', '1 tableta semanal en ayunas con 240 ml agua, mantenerse de pie 30 min'),
('Alendronato', 'Alendronato sódico', 'Tabletas 10 mg', '1 tableta cada 24 hrs en ayunas con agua, de pie 30 min'),
('Actonel', 'Risedronato sódico', 'Tabletas 35 mg', '1 tableta semanal en ayunas con 240 ml agua, de pie 30 min'),
('Actonel', 'Risedronato sódico', 'Tabletas 5 mg', '1 tableta cada 24 hrs en ayunas con agua, de pie 30 min'),
('Risedronato', 'Risedronato sódico', 'Tabletas 150 mg', '1 tableta mensual en ayunas con agua, mantenerse de pie 30 min'),
('Bonviva', 'Ibandronato sódico', 'Tabletas 150 mg', '1 tableta mensual en ayunas con agua, de pie 60 min'),
('Ibandronato', 'Ibandronato sódico', 'Tabletas 150 mg', '1 tableta mensual en ayunas con agua'),
('Bonviva IV', 'Ibandronato sódico', 'Solución inyectable 3 mg/3 ml', '3 mg IV cada 3 meses (infusión >15 seg)'),
('Reclast', 'Ácido zoledrónico', 'Solución IV 5 mg/100 ml', '5 mg IV anual (infusión >15 min)'),
('Zometa', 'Ácido zoledrónico', 'Solución IV 4 mg/100 ml', '4 mg IV cada 3-4 semanas (metástasis ósea) o 4 mg anual'),
('Ácido zoledrónico', 'Ácido zoledrónico', 'Solución IV 5 mg/100 ml', '5 mg IV una vez al año (osteoporosis)'),
-- Anticuerpos monoclonales
('Prolia', 'Denosumab', 'Jeringa precargada 60 mg/1 ml', '60 mg SC cada 6 meses (asociar calcio + vitamina D)'),
('Xgeva', 'Denosumab', 'Vial 120 mg/1.7 ml', '120 mg SC cada 4 semanas (metástasis ósea)'),
('Evenity', 'Romosozumab', 'Jeringa precargada 105 mg/1.17 ml', '2 inyecciones SC (210 mg) una vez al mes por 12 meses'),
-- Anabólicos óseos
('Forteo', 'Teriparatida', 'Pluma inyectable 250 mcg/ml (2.4 ml)', '20 mcg SC cada 24 hrs (máx 2 años de tratamiento)'),
('Tymlos', 'Abaloparatida', 'Pluma inyectable 3120 mcg/1.56 ml', '80 mcg SC cada 24 hrs (máx 18 meses)'),
-- SERM
('Evista', 'Raloxifeno', 'Tabletas 60 mg', '1 tableta cada 24 hrs con o sin alimentos'),
('Raloxifeno', 'Raloxifeno', 'Tabletas 60 mg', '1 tableta cada 24 hrs'),
-- Calcitonina
('Miacalcic', 'Calcitonina de salmón', 'Spray nasal 200 UI/dosis', '1 puff nasal alternando fosas nasales cada 24 hrs'),
('Calcitonina', 'Calcitonina de salmón', 'Solución inyectable 100 UI/1 ml', '100 UI SC/IM cada 24 hrs (fractura aguda, dolor)'),
-- Calcio + Vitamina D
('Caltrate', 'Calcio carbonato + Vitamina D3', 'Tabletas 600 mg / 400 UI', '1 tableta cada 12 hrs con alimentos'),
('Os-Cal', 'Calcio carbonato + Vitamina D3', 'Tabletas 500 mg / 200 UI', '1 tableta cada 12 hrs con alimentos'),
('Calcium Sandoz', 'Calcio gluconolactato + carbonato', 'Tabletas efervescentes 500 mg Ca', '1-2 tabletas disueltas en agua cada 24 hrs'),
('Vitamina D3', 'Colecalciferol', 'Cápsulas 5000 UI', '1 cápsula cada 24 hrs con alimentos (déficit / osteoporosis)'),
('Vitamina D3', 'Colecalciferol', 'Cápsulas 2000 UI', '1-2 cápsulas cada 24 hrs con alimentos (mantenimiento)'),
('Vitamina D3', 'Colecalciferol', 'Gotas 400 UI/gota', '10-20 gotas cada 24 hrs con alimentos'),
('Calcifediol', 'Calcifediol (25-OH vitamina D)', 'Cápsulas blandas 266 mcg', '1 cápsula quincenal o mensual (ajustar según niveles séricos)'),
('Hidroferol', 'Calcifediol', 'Ampollas bebibles 0.266 mg', '1 ampolla mensual o quincenal (según 25-OH vitamina D)'),
('Calcitriol', 'Calcitriol (1,25-dihidroxivitamina D3)', 'Cápsulas 0.25 mcg', '1 cápsula cada 24 hrs (insuficiencia renal / hipoparatiroidismo)'),
('Rocaltrol', 'Calcitriol', 'Cápsulas 0.5 mcg', '1 cápsula cada 24 hrs'),
('Vitamina D3 + K2', 'Colecalciferol / Menaquinona-7', 'Cápsulas 5000 UI / 100 mcg', '1 cápsula cada 24 hrs con alimentos'),
('Ranelato de estroncio', 'Ranelato de estroncio', 'Sobres 2 g', '1 sobre disuelto en agua cada noche al acostarse (en ayunas)');
